
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author 52311
 */
public class OperacionesPila extends javax.swing.JFrame {

    ArrayList<String> lexema, lexemaSinRep;
    String grama = "";
    int cont = 0;
    int inc = 1;

    /**
     * Creates new form OpcionesGrama
     */
    public OperacionesPila() {
        initComponents();
    }

    public OperacionesPila(ArrayList<String> pila) {
        initComponents();
        String cad = "";

//        for (int i = 0; i < pila.size(); i++) {
//            System.out.println("|       " + pila.get(i) + "        |");
//            cad += "|       " + pila.get(i) + "        |\n";
//        }
//        System.out.println("|       " + "        |");
//        cad += "|       " + "_______________" + "        |";
        cad = ajustaEspacios(pila);
        lblPila.setText(cad);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lblPila = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(550, 650));
        setResizable(false);
        getContentPane().setLayout(null);

        pnlFondo.setMaximumSize(new java.awt.Dimension(550, 650));
        pnlFondo.setMinimumSize(new java.awt.Dimension(550, 650));
        pnlFondo.setPreferredSize(new java.awt.Dimension(550, 650));
        pnlFondo.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Operacion");
        pnlFondo.add(jLabel1);
        jLabel1.setBounds(0, 20, 550, 43);

        lblPila.setEditable(false);
        lblPila.setColumns(20);
        lblPila.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        lblPila.setRows(5);
        jScrollPane1.setViewportView(lblPila);

        pnlFondo.add(jScrollPane1);
        jScrollPane1.setBounds(40, 170, 450, 380);

        getContentPane().add(pnlFondo);
        pnlFondo.setBounds(0, 0, 550, 650);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OpcionesGrama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OpcionesGrama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OpcionesGrama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OpcionesGrama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OpcionesGrama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea lblPila;
    private javax.swing.JPanel pnlFondo;
    // End of variables declaration//GEN-END:variables

    private String ajustaEspacios(ArrayList<String> pila) {
        String cad1 = "";
        String cad2 = "";
        String esp = "";
        int tamMax = 0;
        ArrayList<String> p = pila;

        //Saca el valor tamaño máximo
        for (int i = 0; i < p.size(); i++) {
            Integer lon = p.get(i).length();
            if(lon>tamMax){
                tamMax=lon;
            }
        }
        
        //Pone espacios en blanco según el tamaño máximo
        for (int i = 0; i < tamMax; i++) {
            esp+=" ";
        }
        for (int i = 0; i < p.size(); i++) {
            cad1+="     |"+"     "+p.get(i)+espacios(p.get(i).length(),tamMax)+"     |\n";
        }
        cad1+="     |_____";
        for (int i = 0; i <= tamMax; i++) {
            cad1+="_";
        }
        cad1+="_____|";

        return cad1;
    }

    private String espacios(int tamFun, int tamMax) {
        String cad = "";
        //JOptionPane.showMessageDialog(this, "Fun:" + tamFun + "\n" + "Maximo: " + tamMax);
        int i=0;
        int tope = tamMax-tamFun;
        
        //System.out.println("Fun:" + tamFun + "\n" + "Maximo: " + tamMax+"\nAgregar: "+tope);
        while (i<=tope) {
            if(tamFun<=tamMax){
                cad+=" ";
                i++; 
            }else i=tamFun;
            
            //JOptionPane.showMessageDialog(this, tamFun);
        }
        return cad;
    }
}
