
import compilerTools.ErrorLSSL;
import compilerTools.Token;
import java.util.ArrayList;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 52311
 */
public class VentanaErrores extends javax.swing.JFrame {
    String NombreGrama;
    String Gramatica;
    String TokenGramatica;
    String Error;
    /**
     * Creates new form VentanaErrores
     */
    public VentanaErrores() {
        initComponents();
    }
    public void Mostrar(){
     String cadena="";
     cadena="******GRAMATICA\n"
             + NombreGrama+"\n \n"
             +"******GRAMATICA NO VALIDA O INCONCLUSA\n"
             +NombreGrama+"::= "+Gramatica+"\n \n"
             +"******TOKENS UTILIZADOS \n"
             +TokenGramatica+"\n \n"
             +"******SOLUCIONES\n"
             +soluciones(NombreGrama);
     
     txtError.setText(cadena);
    }  
    
    
    public String soluciones(String Cadena){
        String grama="";
        
    switch (Cadena) {
                case "IF":
                    grama="IF-> If Parentesis_A (EXP_LOGICA | Identificador) Parentesis_C \n" ;
                    break;
                case "OP_RETORNO":
                    grama="OP_RETORNO-> OP_Retorno Parentesis_A Parentesis_C \n" ;
                    break;
                case "VARIABLE_PC":
                    grama="VARIABLE_PC-> VARIABLE Punto_Coma \n" ;
                    break;
                case "FUNCION_COMPLETA_PC":
                    grama="FUNCION_COMPLETA_PC-> FUNCION_COMPLETA Punto_Coma \n" ;
                    break;
                case "CICLO_FOR":
                    grama="CICLO_FOR-> For Parentesis_A (VALOR | Identificador) Parentesis_C \n" ;
                    break;
                case "CICLO_WHILE":
                    grama="CICLO_WHILE-> While Parentesis_A (EXP_LOGICA | Identificador) Parentesis_C \n" ;
                    break;
                case "VALOR":
                    grama="VALOR-> (Cadena | Numero | OP_RETORNO) \n" ;
                    break;    
                case "VARIABLE":
                    grama="VARIABLE-> Identificador Op_Asignacion VALOR \n" ;
                    break;
                case "FUNCION":
                    grama="FUNCION-> (OP_Cita | OP_Turno | OP_Iluminacion | OP_Temperatura | OP_Puerta) \n" ;
                    break;   
                case "EXP_LOGICA":
                    grama="EXP_LOGICA-> (VALOR | Identificador) Op_Relacional (VALOR | Identificador) \n" ;
                    break;  
                case "FUNCION_COMPLETA":
                    grama="FUNCION_COMPLETA-> FUNCION Parentesis_A (PARAMETROS | (VALOR | Identificador))? Parentesis_C \n" ;
                    break;     
                case "PARAMETROS":
                    grama="PARAMETROS-> (VALOR | Identificador) (Coma (VALOR | Identificador))+ \n" ;
                    break;      
                case "BLOQUE_INICIO":
                    grama="BLOQUE_INICIO-> INICIO Identificador \n" ;
                    break;     
                  case "BLOQUE_PRINCIPAL":
                    grama="BLOQUE_PRINCIPAL-> PRINCIPAL Parentesis_A Parentesis_C \n" ;
                    break;     
                default:
                    break;
            }
        
        return grama;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondo = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtError = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(550, 650));
        setMinimumSize(new java.awt.Dimension(550, 650));
        setPreferredSize(new java.awt.Dimension(550, 650));
        setResizable(false);
        getContentPane().setLayout(null);

        pnlFondo.setMaximumSize(new java.awt.Dimension(550, 650));
        pnlFondo.setMinimumSize(new java.awt.Dimension(550, 650));
        pnlFondo.setPreferredSize(new java.awt.Dimension(550, 650));
        pnlFondo.setLayout(null);

        txtError.setEditable(false);
        txtError.setColumns(20);
        txtError.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtError.setRows(5);
        jScrollPane1.setViewportView(txtError);

        pnlFondo.add(jScrollPane1);
        jScrollPane1.setBounds(46, 79, 450, 490);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ERROR DETECTADO ");
        pnlFondo.add(jLabel1);
        jLabel1.setBounds(0, 20, 550, 40);

        getContentPane().add(pnlFondo);
        pnlFondo.setBounds(0, 0, 550, 650);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaErrores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaErrores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaErrores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaErrores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaErrores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlFondo;
    public javax.swing.JTextArea txtError;
    // End of variables declaration//GEN-END:variables
}
