// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: src/Lexer.flex

import compilerTools.Token;


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
class Lexer {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\4\1\5\22\0\1\1"+
    "\1\6\1\7\1\0\1\10\1\0\1\11\1\0\1\12"+
    "\1\13\1\14\1\0\1\15\2\0\1\16\1\17\11\20"+
    "\1\0\1\21\1\22\1\23\1\22\2\0\32\24\4\0"+
    "\1\25\1\0\1\26\1\27\1\30\1\31\1\32\1\33"+
    "\1\34\1\35\1\36\1\37\1\24\1\40\1\41\1\42"+
    "\1\43\1\44\1\24\1\45\1\46\1\47\1\50\1\51"+
    "\1\52\1\53\2\24\1\54\1\55\1\56\7\0\1\3"+
    "\73\0\1\24\7\0\1\24\3\0\1\24\3\0\1\24"+
    "\1\0\1\24\6\0\1\24\6\0\1\24\7\0\1\24"+
    "\3\0\1\24\3\0\1\24\1\0\1\24\6\0\1\24"+
    "\u012d\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\4\1\1\3\1\4\1\5\1\1"+
    "\2\6\1\7\1\10\1\11\10\12\1\13\1\1\1\14"+
    "\1\10\1\0\1\15\1\16\1\17\1\0\1\2\2\20"+
    "\2\12\1\21\6\12\2\0\1\12\1\22\6\12\1\0"+
    "\1\2\17\12\1\23\6\12\1\24\57\12\1\25\1\12"+
    "\1\26\3\12\1\27\10\12\1\30\2\12\1\31\1\32"+
    "\2\12";

  private static int [] zzUnpackAction() {
    int [] result = new int[150];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\57\0\57\0\136\0\215\0\274\0\353\0\u011a"+
    "\0\57\0\57\0\57\0\u0149\0\u0178\0\u01a7\0\57\0\215"+
    "\0\215\0\u01d6\0\u0205\0\u0234\0\u0263\0\u0292\0\u02c1\0\u02f0"+
    "\0\u031f\0\57\0\u034e\0\57\0\57\0\274\0\274\0\u037d"+
    "\0\57\0\u03ac\0\u03db\0\57\0\u040a\0\u0439\0\u0468\0\u01d6"+
    "\0\u0497\0\u04c6\0\u04f5\0\u0524\0\u0553\0\u0582\0\u05b1\0\u05e0"+
    "\0\u060f\0\u01d6\0\u063e\0\u066d\0\u069c\0\u06cb\0\u06fa\0\u0729"+
    "\0\u0758\0\u05b1\0\u0787\0\u07b6\0\u07e5\0\u0814\0\u0843\0\u0872"+
    "\0\u08a1\0\u08d0\0\u08ff\0\u092e\0\u095d\0\u098c\0\u09bb\0\u09ea"+
    "\0\u0a19\0\u01d6\0\u0a48\0\u0a77\0\u0aa6\0\u0ad5\0\u0b04\0\u0b33"+
    "\0\u01d6\0\u0b62\0\u0b91\0\u0bc0\0\u0bef\0\u0c1e\0\u0c4d\0\u0c7c"+
    "\0\u0cab\0\u0cda\0\u0d09\0\u0d38\0\u0d67\0\u0d96\0\u0dc5\0\u0df4"+
    "\0\u0e23\0\u0e52\0\u0e81\0\u0eb0\0\u0edf\0\u0f0e\0\u0f3d\0\u0f6c"+
    "\0\u0f9b\0\u0fca\0\u0ff9\0\u1028\0\u1057\0\u1086\0\u10b5\0\u10e4"+
    "\0\u1113\0\u1142\0\u1171\0\u11a0\0\u11cf\0\u11fe\0\u122d\0\u125c"+
    "\0\u128b\0\u12ba\0\u12e9\0\u1318\0\u1347\0\u1376\0\u13a5\0\u13d4"+
    "\0\u01d6\0\u1403\0\u01d6\0\u1432\0\u1461\0\u1490\0\u01d6\0\u14bf"+
    "\0\u14ee\0\u151d\0\u154c\0\u157b\0\u15aa\0\u15d9\0\u1608\0\u01d6"+
    "\0\u1637\0\u1666\0\u01d6\0\u01d6\0\u1695\0\u16c4";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[150];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\2\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\4\22\1\23\2\22\1\24\2\22"+
    "\1\25\5\22\1\26\1\27\1\22\1\30\2\22\1\31"+
    "\1\22\1\32\1\33\1\34\61\0\1\3\77\0\1\35"+
    "\33\0\2\36\4\0\1\36\1\37\47\36\24\0\30\40"+
    "\14\0\1\41\61\0\1\42\1\0\1\43\57\0\1\44"+
    "\1\45\55\0\2\16\55\0\2\22\3\0\30\22\22\0"+
    "\2\22\3\0\12\22\1\46\15\22\22\0\2\22\3\0"+
    "\17\22\1\47\10\22\22\0\2\22\3\0\7\22\1\50"+
    "\4\22\1\51\13\22\22\0\2\22\3\0\24\22\1\52"+
    "\3\22\22\0\2\22\3\0\6\22\1\53\21\22\22\0"+
    "\2\22\3\0\6\22\1\54\15\22\1\55\3\22\22\0"+
    "\2\22\3\0\11\22\1\56\16\22\60\0\1\41\20\0"+
    "\2\40\3\0\30\40\3\0\14\57\1\60\42\57\2\43"+
    "\1\3\2\43\1\4\51\43\17\0\2\45\55\0\2\22"+
    "\3\0\23\22\1\61\4\22\22\0\2\22\3\0\21\22"+
    "\1\62\6\22\22\0\2\22\3\0\24\22\1\63\3\22"+
    "\22\0\2\22\3\0\6\22\1\64\21\22\22\0\2\22"+
    "\3\0\23\22\1\65\4\22\22\0\2\22\3\0\15\22"+
    "\1\66\12\22\22\0\2\22\3\0\21\22\1\67\6\22"+
    "\22\0\2\22\3\0\12\22\1\70\15\22\3\0\14\57"+
    "\1\71\56\57\1\71\1\57\1\72\40\57\17\0\2\22"+
    "\3\0\2\22\1\73\25\22\22\0\2\22\3\0\1\22"+
    "\1\74\26\22\22\0\2\22\3\0\21\22\1\75\6\22"+
    "\22\0\2\22\3\0\24\22\1\76\3\22\22\0\2\22"+
    "\3\0\20\22\1\77\7\22\22\0\2\22\3\0\16\22"+
    "\1\100\11\22\22\0\2\22\3\0\14\22\1\101\13\22"+
    "\3\0\14\57\1\71\1\57\1\3\40\57\17\0\2\22"+
    "\3\0\1\22\1\102\26\22\22\0\2\22\3\0\2\22"+
    "\1\103\3\22\1\104\13\22\1\105\5\22\22\0\2\22"+
    "\3\0\23\22\1\106\4\22\22\0\2\22\3\0\21\22"+
    "\1\107\6\22\22\0\2\22\3\0\1\22\1\110\26\22"+
    "\22\0\2\22\3\0\17\22\1\111\10\22\22\0\2\22"+
    "\3\0\6\22\1\112\21\22\22\0\2\22\3\0\2\22"+
    "\1\113\1\22\1\114\23\22\22\0\2\22\3\0\20\22"+
    "\1\115\7\22\22\0\2\22\3\0\16\22\1\116\11\22"+
    "\22\0\2\22\3\0\23\22\1\117\4\22\22\0\2\22"+
    "\3\0\2\22\1\120\25\22\22\0\2\22\3\0\16\22"+
    "\1\121\11\22\22\0\2\22\3\0\2\22\1\122\1\123"+
    "\2\22\1\124\13\22\1\125\5\22\22\0\2\22\3\0"+
    "\1\22\1\126\26\22\22\0\2\22\3\0\10\22\1\127"+
    "\17\22\22\0\2\22\3\0\2\22\1\130\25\22\22\0"+
    "\2\22\3\0\2\22\1\131\25\22\22\0\2\22\3\0"+
    "\4\22\1\132\23\22\22\0\2\22\3\0\2\22\1\133"+
    "\25\22\22\0\2\22\3\0\1\22\1\134\26\22\22\0"+
    "\2\22\3\0\4\22\1\135\23\22\22\0\2\22\3\0"+
    "\2\22\1\136\25\22\22\0\2\22\3\0\22\22\1\137"+
    "\5\22\22\0\2\22\3\0\24\22\1\140\3\22\22\0"+
    "\2\22\3\0\2\22\1\122\13\22\1\141\1\22\1\142"+
    "\2\22\1\143\4\22\22\0\2\22\3\0\6\22\1\144"+
    "\21\22\22\0\2\22\3\0\16\22\1\145\11\22\22\0"+
    "\2\22\3\0\10\22\1\146\17\22\22\0\2\22\3\0"+
    "\6\22\1\147\21\22\22\0\2\22\3\0\23\22\1\150"+
    "\4\22\22\0\2\22\3\0\2\22\1\151\1\22\1\152"+
    "\15\22\1\105\5\22\22\0\2\22\3\0\23\22\1\153"+
    "\4\22\22\0\2\22\3\0\13\22\1\154\14\22\22\0"+
    "\2\22\3\0\23\22\1\155\4\22\22\0\2\22\3\0"+
    "\3\22\1\156\24\22\22\0\2\22\3\0\24\22\1\157"+
    "\3\22\22\0\2\22\3\0\21\22\1\160\6\22\22\0"+
    "\2\22\3\0\12\22\1\161\15\22\22\0\2\22\3\0"+
    "\16\22\1\162\11\22\22\0\2\22\3\0\4\22\1\163"+
    "\23\22\22\0\2\22\3\0\2\22\1\164\25\22\22\0"+
    "\2\22\3\0\16\22\1\165\11\22\22\0\2\22\3\0"+
    "\24\22\1\166\3\22\22\0\2\22\3\0\3\22\1\167"+
    "\24\22\22\0\2\22\3\0\6\22\1\170\21\22\22\0"+
    "\2\22\3\0\24\22\1\171\3\22\22\0\2\22\3\0"+
    "\2\22\1\172\25\22\22\0\2\22\3\0\2\22\1\173"+
    "\25\22\22\0\2\22\3\0\12\22\1\172\15\22\22\0"+
    "\2\22\3\0\6\22\1\174\21\22\22\0\2\22\3\0"+
    "\17\22\1\175\10\22\22\0\2\22\3\0\6\22\1\176"+
    "\21\22\22\0\2\22\3\0\5\22\1\177\22\22\22\0"+
    "\2\22\3\0\6\22\1\200\21\22\22\0\2\22\3\0"+
    "\21\22\1\201\6\22\22\0\2\22\3\0\5\22\1\202"+
    "\22\22\22\0\2\22\3\0\22\22\1\203\5\22\22\0"+
    "\2\22\3\0\21\22\1\204\6\22\22\0\2\22\3\0"+
    "\21\22\1\205\6\22\22\0\2\22\3\0\2\22\1\206"+
    "\25\22\22\0\2\22\3\0\21\22\1\207\6\22\22\0"+
    "\2\22\3\0\3\22\1\210\24\22\22\0\2\22\3\0"+
    "\25\22\1\211\2\22\22\0\2\22\3\0\27\22\1\212"+
    "\22\0\2\22\3\0\15\22\1\213\12\22\22\0\2\22"+
    "\3\0\2\22\1\214\25\22\22\0\2\22\3\0\14\22"+
    "\1\177\13\22\22\0\2\22\3\0\6\22\1\164\21\22"+
    "\22\0\2\22\3\0\12\22\1\215\15\22\22\0\2\22"+
    "\3\0\21\22\1\216\6\22\22\0\2\22\3\0\14\22"+
    "\1\203\13\22\22\0\2\22\3\0\14\22\1\217\13\22"+
    "\22\0\2\22\3\0\17\22\1\220\10\22\22\0\2\22"+
    "\3\0\12\22\1\221\15\22\22\0\2\22\3\0\20\22"+
    "\1\222\7\22\22\0\2\22\3\0\21\22\1\223\6\22"+
    "\22\0\2\22\3\0\21\22\1\224\6\22\22\0\2\22"+
    "\3\0\2\22\1\215\25\22\22\0\2\22\3\0\6\22"+
    "\1\225\21\22\22\0\2\22\3\0\15\22\1\222\12\22"+
    "\22\0\2\22\3\0\17\22\1\203\10\22\22\0\2\22"+
    "\3\0\4\22\1\226\23\22\22\0\2\22\3\0\6\22"+
    "\1\172\21\22\3\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5875];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\5\1\3\11\3\1\1\11\12\1\1\11"+
    "\1\1\2\11\1\0\2\1\1\11\1\0\1\1\1\11"+
    "\12\1\2\0\10\1\1\0\135\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[150];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
    private Token token(String lexeme, String lexicalComp,int line, int column){
        return new Token(lexeme,lexicalComp, line+1, column+1);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return token(yytext(), "Error", yyline, yycolumn);
            }
            // fall through
          case 27: break;
          case 2:
            { /* Ignorar */
            }
            // fall through
          case 28: break;
          case 3:
            { return token(yytext(), "Parentesis_A", yyline, yycolumn);
            }
            // fall through
          case 29: break;
          case 4:
            { return token(yytext(), "Parentesis_C", yyline, yycolumn);
            }
            // fall through
          case 30: break;
          case 5:
            { return token(yytext(), "Coma", yyline, yycolumn);
            }
            // fall through
          case 31: break;
          case 6:
            { return token(yytext(), "Numero", yyline, yycolumn);
            }
            // fall through
          case 32: break;
          case 7:
            { return token(yytext(), "Punto_Coma", yyline, yycolumn);
            }
            // fall through
          case 33: break;
          case 8:
            { return token(yytext(), "Op_Relacional", yyline, yycolumn);
            }
            // fall through
          case 34: break;
          case 9:
            { return token(yytext(), "Op_Asignacion", yyline, yycolumn);
            }
            // fall through
          case 35: break;
          case 10:
            { return token(yytext(), "Error_2", yyline, yycolumn);
            }
            // fall through
          case 36: break;
          case 11:
            { return token(yytext(), "Llave_A", yyline, yycolumn);
            }
            // fall through
          case 37: break;
          case 12:
            { return token(yytext(), "Llave_C", yyline, yycolumn);
            }
            // fall through
          case 38: break;
          case 13:
            { return token (yytext(), "Cadena", yyline, yycolumn);
            }
            // fall through
          case 39: break;
          case 14:
            { return token(yytext(), "Identificador", yyline, yycolumn);
            }
            // fall through
          case 40: break;
          case 15:
            { return token(yytext(), "Op_Logico", yyline, yycolumn);
            }
            // fall through
          case 41: break;
          case 16:
            { return token(yytext(), "Error_1", yyline, yycolumn);
            }
            // fall through
          case 42: break;
          case 17:
            { return token(yytext(), "If", yyline, yycolumn);
            }
            // fall through
          case 43: break;
          case 18:
            { return token(yytext(), "For", yyline, yycolumn);
            }
            // fall through
          case 44: break;
          case 19:
            { return token(yytext(), "While", yyline, yycolumn);
            }
            // fall through
          case 45: break;
          case 20:
            { return token(yytext(), "Return", yyline, yycolumn);
            }
            // fall through
          case 46: break;
          case 21:
            { return token(yytext(), "OP_Iluminacion", yyline, yycolumn);
            }
            // fall through
          case 47: break;
          case 22:
            { return token(yytext(), "OP_Retorno", yyline, yycolumn);
            }
            // fall through
          case 48: break;
          case 23:
            { return token(yytext(), "OP_Temperatura", yyline, yycolumn);
            }
            // fall through
          case 49: break;
          case 24:
            { return token(yytext(), "OP_Turno", yyline, yycolumn);
            }
            // fall through
          case 50: break;
          case 25:
            { return token(yytext(), "OP_Cita", yyline, yycolumn);
            }
            // fall through
          case 51: break;
          case 26:
            { return token(yytext(), "OP_Puerta", yyline, yycolumn);
            }
            // fall through
          case 52: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
