
import java.util.ArrayList;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author 52311
 */
public class OpcionesGrama extends javax.swing.JFrame {

    ArrayList<String> lexema, lexemaSinRep;
    String grama = "";
    int cont = 0;
    int inc=1;

    /**
     * Creates new form OpcionesGrama
     */
    public OpcionesGrama() {
        initComponents();
    }

    public OpcionesGrama(ArrayList<String> lexe) {
        this();
        lexema = lexe;
        lexemaSinRep = new ArrayList<>();
        Gramaticas();
        lexe.clear();

        // JArea.setText(MostrarTokens());
        // lexe.clear();
    }

    public void Gramaticas() {
        for(String lex:lexema){
            if(!lexemaSinRep.contains(lex)){
                lexemaSinRep.add(lex);
            }
        }
        for(String lexSinRep: lexemaSinRep){
            switch (lexSinRep) {
                case "IF":
                    grama+="\n "+(inc++)+" IF-> If Parentesis_A (EXP_LOGICA | Identificador) Parentesis_C \n" ;
                    break;
                case "OP_RETORNO":
                    grama+="\n "+(inc++)+" OP_RETORNO-> OP_Retorno Parentesis_A Parentesis_C \n" ;
                    break;
                case "VARIABLE_PC":
                    grama+="\n "+(inc++)+" VARIABLE_PC-> VARIABLE Punto_Coma \n" ;
                    break;
                case "FUNCION_COMPLETA_PC":
                    grama+="\n "+(inc++)+" FUNCION_COMPLETA_PC-> FUNCION_COMPLETA Punto_Coma \n" ;
                    break;
                case "CICLO_FOR":
                    grama+="\n "+(inc++)+" CICLO_FOR-> For Parentesis_A (VALOR | Identificador) Parentesis_C \n" ;
                    break;
                case "CICLO_WHILE":
                    grama+="\n "+(inc++)+"  CICLO_WHILE-> While Parentesis_A (EXP_LOGICA | Identificador) Parentesis_C \n" ;
                    break;
                case "VALOR":
                    grama+="\n "+(inc++)+" VALOR-> (Cadena | Numero | OP_RETORNO) \n" ;
                    break;    
                case "VARIABLE":
                    grama+="\n "+(inc++)+" VARIABLE-> Identificador Op_Asignacion VALOR \n" ;
                    break;
                case "FUNCION":
                    grama+="\n "+(inc++)+" FUNCION-> (OP_Cita | OP_Turno | OP_Iluminacion | OP_Temperatura | OP_Puerta) \n" ;
                    break;   
                case "EXP_LOGICA":
                    grama+="\n "+(inc++)+" EXP_LOGICA-> (VALOR | Identificador) Op_Relacional (VALOR | Identificador) \n" ;
                    break;  
                case "FUNCION_COMPLETA":
                    grama+="\n "+(inc++)+" FUNCION_COMPLETA-> FUNCION Parentesis_A (PARAMETROS | (VALOR | Identificador))? Parentesis_C \n" ;
                    break;     
                case "PARAMETROS":
                    grama+="\n "+(inc++)+" PARAMETROS-> (VALOR | Identificador) (Coma (VALOR | Identificador))+ \n" ;
                    break;      
                default:
                    break;
            }
           
        }
        JArea.setText(grama);
        
    }

    private String MostrarTokens() {
        while (cont <= lexema.size() - 1) {
            grama += lexema.get(cont) + "\n";
            cont++;
        }
        return grama;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        JArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        JArea.setColumns(20);
        JArea.setRows(5);
        jScrollPane1.setViewportView(JArea);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 153));
        jLabel1.setText("GRAMATICAS USADAS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(93, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OpcionesGrama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OpcionesGrama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OpcionesGrama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OpcionesGrama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OpcionesGrama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea JArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
