
import compilerTools.ErrorLSSL;
import compilerTools.Token;
import java.util.ArrayList;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 52311
 */
public class VentanaErrores extends javax.swing.JFrame {
    String NombreGrama;
    String Gramatica;
    String TokenGramatica;
    String Error;
    /**
     * Creates new form VentanaErrores
     */
    public VentanaErrores() {
        initComponents();
    }
   public VentanaErrores(String NombreGra,String Grama,String TokenGrama) {
        initComponents();
        NombreGrama=NombreGra;
        Gramatica=Grama;
        TokenGramatica=TokenGrama;
        Mostrar();
        
      }
    public void Mostrar(){
     String cadena="";
     cadena="******GRAMATICA\n"
             + NombreGrama+"\n \n"
             +"******GRAMATICA NO VALIDA O INCONCLUSA\n"
             +NombreGrama+"::= "+Gramatica+"\n \n"
             +"******TOKENS UTILIZADOS \n"
             +TokenGramatica+"\n \n"
             +"******SOLUCIONES\n"
             +soluciones(NombreGrama);
     
     jTextArea1.setText(cadena);
    }  
    
    
    public String soluciones(String Cadena){
        String grama="";
        
    switch (Cadena) {
                case "IF":
                    grama="IF-> If Parentesis_A (EXP_LOGICA | Identificador) Parentesis_C \n" ;
                    break;
                case "OP_RETORNO":
                    grama="OP_RETORNO-> OP_Retorno Parentesis_A Parentesis_C \n" ;
                    break;
                case "VARIABLE_PC":
                    grama="VARIABLE_PC-> VARIABLE Punto_Coma \n" ;
                    break;
                case "FUNCION_COMPLETA_PC":
                    grama="FUNCION_COMPLETA_PC-> FUNCION_COMPLETA Punto_Coma \n" ;
                    break;
                case "CICLO_FOR":
                    grama="CICLO_FOR-> For Parentesis_A (VALOR | Identificador) Parentesis_C \n" ;
                    break;
                case "CICLO_WHILE":
                    grama="CICLO_WHILE-> While Parentesis_A (EXP_LOGICA | Identificador) Parentesis_C \n" ;
                    break;
                case "VALOR":
                    grama="VALOR-> (Cadena | Numero | OP_RETORNO) \n" ;
                    break;    
                case "VARIABLE":
                    grama="VARIABLE-> Identificador Op_Asignacion VALOR \n" ;
                    break;
                case "FUNCION":
                    grama="FUNCION-> (OP_Cita | OP_Turno | OP_Iluminacion | OP_Temperatura | OP_Puerta) \n" ;
                    break;   
                case "EXP_LOGICA":
                    grama="EXP_LOGICA-> (VALOR | Identificador) Op_Relacional (VALOR | Identificador) \n" ;
                    break;  
                case "FUNCION_COMPLETA":
                    grama="FUNCION_COMPLETA-> FUNCION Parentesis_A (PARAMETROS | (VALOR | Identificador))? Parentesis_C \n" ;
                    break;     
                case "PARAMETROS":
                    grama="PARAMETROS-> (VALOR | Identificador) (Coma (VALOR | Identificador))+ \n" ;
                    break;      
                case "BLOQUE_INICIO":
                    grama="BLOQUE_INICIO-> INICIO Identificador \n" ;
                    break;     
                  case "BLOQUE_PRINCIPAL":
                    grama="BLOQUE_PRINCIPAL-> PRINCIPAL Parentesis_A Parentesis_C \n" ;
                    break;     
                default:
                    break;
            }
        
        return grama;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("ERROR DETECTADO ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaErrores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaErrores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaErrores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaErrores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaErrores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
